package com.pspotl.sidebranden.builder.enums;

public enum BinaryServiceType {

    HV_BIN_APP_ICON_READ,

    HV_BIN_DEPLOY_METADATA_IMAGE_READ,

    HV_BIN_DEPLOY_ANDROID_METADATA_PHONE_IMAGE_READ,

    HV_BIN_DEPLOY_ANDROID_METADATA_TABLET_7INCH_IMAGE_READ,

    HV_BIN_DEPLOY_ANDROID_METADATA_TABLET_10INCH_IMAGE_READ,

    HV_BIN_DEPLOY_METADATA_PHONE_IMAGE_READ,

    HV_BIN_DEPLOY_METADATA_TABLET_SMALL_IMAGE_READ,

    HV_BIN_DEPLOY_METADATA_TABLET_LARGE_IMAGE_READ

}
