package com.pspotl.sidebranden.builder.enums;

public enum ProjectServiceType {
    HV_MSG_PROJECT_IMPORT_START_INFO,
    HV_MSG_PROJECT_IMPORT_STATUS_INFO,
    HV_MSG_PROJECT_IMPORT_COMPLETE_INFO,
    HV_MSG_WORKSPACE_CREATE_INFO_FROM_BRANCH,
    HV_MSG_PROJECT_CREATE_INFO_FROM_BRANCH,
    HV_MSG_PROJECT_CREATE_INFO,
    HV_MSG_PROJECT_CREATE_GITHUB_CLONE_INFO,
    HV_MSG_PROJECT_MULTI_PROFILE_VCS_CLONE_INFO,

    HV_MSG_PROJECT_CREATE_GITHUB_CLONE_INFO_FROM_BRANCH,
    HV_MSG_PROJECT_PULL_GITHUB_CLONE_INFO,
    HV_MSG_PROJECT_UPDATE_PUSH_GITHUB_INFO,

    HV_MSG_PROJECT_IMPORT_ZIP_UPLOAD_INFO,

    HV_MSG_PROJECT_APP_CONFIG_INFO,
    HV_MSG_PROJECT_APP_CONFIG_IMAGE_LIST_INFO,
    HV_MSG_PROEJCT_PULL_INFO_FROM_BRANCH,
    HV_MSG_PROEJCT_PULL_INFO,

    HV_BIN_MSG_PROJECT_PROVIONING_PROFILE_UPLOAD_INFO,
    HV_MSG_APPICON_IMAGE_LOAD_INFO,
    HV_MSG_APPICON_IMAGE_LOAD_INFO_FROM_BRANCH,
    HV_MSG_WINDOWS_CONFIG_LIST_INFO,
    HV_MSG_WINDOWS_CONFIG_LIST_INFO_FROM_BRANCH,
    HV_MSG_APPFILE_DOWNLOAD_INFO,
    HV_MSG_APPFILE_DOWNLOAD_INFO_FROM_BRANCH,

    BIN_FILE_ZIPFILE_SEND_INFO,
    BIN_FILE_APP_ICON_APPEND_SEND_INFO,
    BIN_FILE_APP_ICON_UPDATE_SEND_INFO,
    BIN_FILE_PROFILE_TEMPLATE_SEND_INFO,
    BIN_FILE_PROFILE_TEMPLATE_UPDATE_SEND_INFO,
    BIN_FILE_IOS_KEY_FILE_TEMPLATE_SEND_INFO,
    BIN_FILE_IOS_KEY_FILE_TEMPLATE_DEPLOY_SEND_INFO,
    BIN_FILE_IOS_ALL_KEY_FILE_SEND_INFO,
    BIN_FILE_IOS_ALL_KEY_FILE_UPDATE_SEND_INFO,

    MV_MSG_PROJECT_EXPORT_ZIP_REQUEST_INFO_BRNACH,
    HV_MSG_PROJECT_EXPORT_STATUS_INFO,
    MV_HSG_PROJECT_EXPORT_ZIP_DOWNLOAD_INFO,

    HV_MSG_PROJECT_TEMPLATE_LIST_INFO,
    HV_MSG_PROJECT_TEMPLATE_CREATE_INFO,

    HV_MSG_PROJECT_MULTI_PROFILE_TEMPLATE_CREATE_INFO,
    HV_MSG_PROJECT_TEMPLATE_STATUS_INFO,
    HV_MSG_PROJECT_GENERAL_APP_CREATE_INFO,
    HV_MSG_BUILD_GENERAL_APP_INFO,

    HV_MSG_GENERAL_ANDROID_DEBUG_BUILD,
    HV_MSG_GENERAL_ANDROID_RELEASE_BUILD,
    HV_MSG_GENERAL_ANDROID_AAB_DEBUG_BUILD,
    HV_MSG_GENERAL_ANDROID_AAB_RELEASE_BUILD,
    HV_MSG_GENERAL_IOS_DEBUG_BUILD,
    HV_MSG_GENERAL_IOS_RELEASE_BUILD,

    HV_MSG_TEMPLATE_PLUGIN_LIST_INFO,
    HV_MSG_TEMPLATE_PLUGIN_ADD_INFO,
    HV_MSG_TEMPLATE_PLUGIN_REMOVE_INFO,
    HV_MSG_TEMPLATE_PLUGINS_INFO,

    HV_MSG_PROJECT_SERVER_CONFIG_LIST_INFO,
    HV_MSG_PROJECT_TEMPLATE_UPDATE_INFO,
    HV_MSG_PROJECT_SERVER_CONFIG_UPDATE_STATUS_INFO,
    HV_MSG_DEPLOY_SETTING_STATUS_INFO,
    HV_MSG_DEPLOY_TASK_UPDATE_STATUS_INFO,
    HV_MSG_PROJECT_iOS_APPCONFIG_LIST_INFO,

    HV_MSG_PROJECT_IOS_ALL_GETINFORMATION_LIST_INFO,
    HV_MSG_PROJECT_ANDROID_ALL_GETCONFIG_LIST_INFO,

    HV_MSG_PROJECT_UPDATE_VCS_MULTI_PROFILE_CONFIG_UPDATE_INFO,
}
