package com.pspotl.sidebranden.manager.enums;

public enum ClientMessageType {
    HV_MSG_USER_LOGIN_SESSION_INFO,
    HV_MSG_BRANCH_WEBSOCKET_CONNECTION_INFO,
    HV_MSG_CONNETCION_CHECK_INFO,
    HV_MSG_CONNETCION_CHECK_INFO_FROM_HEADQUATER,

    HV_MSG_LOG_INFO,
    HV_MSG_FORCE_LOGOUT,
    HV_MSG_WORKSPACE_CREATE_INFO,
    HV_MSG_WORKSPACE_CREATE_INFO_FROM_BRANCH,
    HV_MSG_PROJECT_CREATE_INFO,
    HV_MSG_PROJECT_CREATE_GITHUB_CLONE_INFO,
    HV_MSG_PROJECT_CREATE_GITHUB_CLONE_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_MULTI_PROFILE_VCS_CLONE_INFO,

    HV_MSG_PROJECT_CREATE_INFO_FROM_HEADQUATER,
    MV_MSG_PROJECT_EXPORT_ZIP_REQUEST_INFO_BRNACH,
    MV_HSG_PROJECT_EXPORT_ZIP_DOWNLOAD_INFO_HEADQUATER,
    HV_MSG_PROJECT_EXPORT_STATUS_INFO_FROM_HEADQUATER,
    MV_HSG_PROJECT_EXPORT_ZIP_DOWNLOAD_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_IMPORT_STATUS_INFO_FROM_BRANCH,
    HV_MSG_PROJECT_IMPORT_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_APP_CONFIG_INFO,
    HV_MSG_PROJECT_TEMPLATE_LIST_INFO,
    HV_MSG_PROJECT_TEMPLATE_CREATE_INFO,
    HV_MSG_PROJECT_MULTI_PROFILE_TEMPLATE_CREATE_INFO,
    HV_MSG_PROJECT_TEMPLATE_UPDATE_INFO,
    HV_MSG_PROJECT_UPDATE_MULTI_PROFILE_CONFIG_UPDATE_INFO,
    HV_MSG_PROJECT_UPDATE_MULTI_PROFILE_CONFIG_UPDATE_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_UPDATE_VCS_MULTI_PROFILE_CONFIG_UPDATE_INFO,
    HV_MSG_PROJECT_UPDATE_VCS_MULTI_PROFILE_CONFIG_UPDATE_INFO_FROM_HEADQUATER,

    HV_MSG_BUILD_STATUS_INFO_FROM_HEADQUATER,
    HV_MSG_DEBUG_BUILD,
    HV_MSG_RELEASE_BUILD,
    HV_MSG_AAB_DEBUG_BUILD,
    HV_MSG_AAB_RELEASE_BUILD,
    HV_MSG_MULTI_PROFILE_IOS_BUILD,

    HV_MSG_GENERAL_ANDROID_DEBUG_BUILD,
    HV_MSG_GENERAL_ANDROID_RELEASE_BUILD,
    HV_MSG_GENERAL_ANDROID_AAB_DEBUG_BUILD,
    HV_MSG_GENERAL_ANDROID_AAB_RELEASE_BUILD,
    HV_MSG_GENERAL_IOS_DEBUG_BUILD,
    HV_MSG_GENERAL_IOS_RELEASE_BUILD,

    HV_MSG_LOG_INFO_FROM_BRANCH,
    HV_MSG_BRANCH_INFO,

    HV_MSG_DEPLOY_ALPHA_INFO,
    HV_MSG_DEPLOY_BETA_INFO,
    HV_MSG_DEPLOY_REAL_DEPLOY_INFO,
    HV_MSG_DEPLOY_STATUS_INFO,

    HV_MSG_PLUGIN_LIST_INFO,
    HV_MSG_PLUGIN_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_PLUGIN_ADD_LIST_INFO,
    HV_MSG_PLUGIN_ADD_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_PLUGIN_REMOVE_LIST_INFO,
    HV_MSG_PLUGIN_REMOVE_LIST_INFO_FROM_HEADQUATER,

    MV_MSG_SIGNIN_KEY_ADD_INFO,
    MV_MSG_SIGNIN_KEY_ADD_INFO_FROM_HEADQUATER,

    HV_MSG_LOGFILE_DOWNLOAD_INFO,

    HV_MSG_APPFILE_DOWNLOAD_INFO,

    HV_MSG_APPICON_IMAGE_LOAD_INFO,

    HV_MSG_DISCONNECT,
    HV_MSG_DISCONNECT_FROM_BRANCH,

    HV_MSG_BRANCH_SESSID_INFO,
    HV_MSG_HEADQUATER_SESSID_INFO,
    HV_MSG_BRANCH_SESSID_INFO_FROM_BRANCH,

    HV_MSG_SEND_FILE_INFO,
    HV_MSG_SEND_FILE_BLOB,
    HV_MSG_SEND_FILE_INFO_FROM_BRANCH,

    HV_MSG_APP_DOWNLOAD_STATUS_INFO,
    HV_MSG_APP_DOWNLOAD_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_WINDOWS_CONFIG_LIST_INFO,
    HV_MSG_WINDOWS_CONFIG_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_PONG_CONN_CHK,
    HV_MSG_PROEJCT_PULL_INFO,

    BIN_FILE_SIGNINGKEY_SEND_INFO,
    BIN_FILE_ZIPFILE_SEND_INFO,
    BIN_FILE_APP_ICON_APPEND_SEND_INFO,
    BIN_FILE_APP_ICON_APPEND_SEND_INFO_FROM_HEADQUATER,
    BIN_FILE_APP_ICON_UPDATE_SEND_INFO,
    BIN_FILE_PROFILE_TEMPLATE_SEND_INFO,
    BIN_FILE_PROFILE_TEMPLATE_UPDATE_SEND_INFO,
    BIN_FILE_IOS_KEY_FILE_TEMPLATE_SEND_INFO,
    BIN_FILE_IOS_KEY_FILE_TEMPLATE_DEPLOY_SEND_INFO,
    BIN_FILE_IOS_ALL_KEY_FILE_SEND_INFO,
    BIN_FILE_IOS_ALL_KEY_FILE_UPDATE_SEND_INFO,
    BIN_FILE_IOS_ALL_KEY_FILE_UPDATE_SEND_INFO_FROM_HEADQUATER,
    BIN_FILE_PROFILE_TEMPLATE_UPDATE_SEND_INFO_FROM_HEADQUATER,

    BIN_FILE_PROFILE_TEMPLATE_SEND_INFO_FROM_HEADQUATER,
    BIN_FILE_IOS_KEY_FILE_TEMPLATE_SEND_INFO_FROM_HEADQUATER,
    BIN_FILE_IOS_KEY_FILE_TEMPLATE_DEPLOY_SEND_INFO_FROM_HEADQUATER,
    BIN_FILE_IOS_ALL_KEY_FILE_SEND_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_APP_CONFIG_IMAGE_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_PULL_GITHUB_CLONE_INFO_FROM_HEADQUATER,

    CL_MSG_UPDATE_CHECK,

    HV_MSG_PROJECT_TEMPLATE_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_PROJECT_TEMPLATE_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_TEMPLATE_PLUGIN_LIST_INFO,
    HV_MSG_TEMPLATE_PLUGIN_ADD_INFO,
    HV_MSG_TEMPLATE_PLUGIN_REMOVE_INFO,
    HV_MSG_TEMPLATE_PLUGINS_INFO,

    HV_MSG_PROJECT_SERVER_CONFIG_LIST_INFO,
    HV_MSG_PROJECT_SERVER_CONFIG_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_PROJECT_SERVER_CONFIG_UPDATE_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_iOS_APPCONFIG_LIST_INFO,
    HV_MSG_PROJECT_IOS_ALL_GETINFORMATION_LIST_INFO,
    HV_MSG_PROJECT_IOS_ALL_GETINFORMATION_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_ANDROID_ALL_GETCONFIG_LIST_INFO,
    HV_MSG_PROJECT_ANDROID_ALL_GETCONFIG_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_BUILD_ALL_MULTI_PROFILE_LIST_INTO,
    HV_MSG_BUILD_ALL_MULTI_PROFILE_LIST_INTO_FROM_HEADQUATER,
    HV_MSG_BUILD_SET_ACTIVE_PROFILE_INFO_FROM_HEADQUATER,
    HV_MSG_BUILD_GET_MULTI_PROFILE_APPCONFIG_LIST_INFO,
    HV_MSG_BUILD_GET_MULTI_PROFILE_APPCONFIG_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_DEPLOY_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_DEPLOY_SETTING_INIT_INFO,
    HV_MSG_DEPLOY_TASK_UPDATE_STATUS_INFO,
    HV_MSG_DEPLOY_METADATA_UPDATE_STATUS_INFO,

    HV_MSG_DEPLOY_TASK_SEARCH_STATUS_INFO,
    HV_MSG_DEPLOY_TASK_SEARCH_STATUS_INFO_FROM_HEADQUATER,
    HV_MSG_DEPLOY_TASK_UPDATE_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_DEPLOY_METADATA_SEARCH_STATUS_INFO,
    HV_MSG_DEPLOY_METADATA_UPDATE_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_DEPLOY_METADATA_IMAGE_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_iOS_APPCONFIG_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_DEPLOY_SETTING_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_GENERAL_APP_CREATE_INFO,
    HV_MSG_PROJECT_GENERAL_APP_CREATE_INFO_FROM_HEADQUATER,
    HV_MSG_BUILD_GENERAL_APP_INFO,
    HV_MSG_BUILD_GENERAL_APP_INFO_FROM_HEADQUATER
}
