package com.pspotl.sidebranden.manager.enums;

public enum PayloadKeyType {
    email,
    error,
    result,
    sessType,
    android,
    ios,
    platform,
    hqKey,
    hqKeyPassword,
    managerClusterId,
    branchUserId,
    Project,
    AppName,
    iOSProjectName,
    projectName,
    branchName,
    branchSettingObj,
    filename,
    product_type,
    profile_type,
    release_type,
    profile_key,
    profile_password,
    adminID,
    domainID,
    userID,
    workspaceID,
    projectID,
    projectDirName,
    language,
    ApplicationID,
    AppVersion,
    AppVersionCode,
    BuildSettings,
    BuildSettingsGson,


    vcsType,
    repositoryId,
    repositoryPassword,
    repositoryURL,


    PackageName,
    MinTargetVersion,
    signingkeyID,
    signingkey_path,
    signingkey_type,
    profilePath,
    zipFileName,
    appIconFileName,

    jsonRepository,
    jsonApplyConfig,
    jsonSigningkey,
    jsonBranchSetting,
    jsonProfileDebug,
    jsonProfileRelease,
    build_id,
    workspace_id,
    workspace_name,
    projectDirPath,

    superadmin,
    build,
    buildType,
    key_name,
    key_password,
    key_alias,
    android_key_store_password,
    role_name,
    vcs_name,

    sampleProjectYn,
    phone_number,
    templateVersion
}
