spring:
  profiles:
    active : local
---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  # JDBC Connection url for the database
  datasource:
    #      jdbc-url: jdbc:mariadb:replication://localhost:3307/whive?useUnicode=true&serverTimezone=Asia/Seoul,localhost:3308/whive?useUnicode=true&serverTimezone=Asia/Seoul
    #      username: root
    #      password: password
    #      jdbc:mariadb://127.0.0.1/W_Hive?characterEncoding=UTF-8&serverTimezone=UTC
    # ENC(ZSx0fLcJh9hLLGTHaEovWHNfFsaAlIERUIieJ1fYphbIjTlSu0w3oai0o78Wc9BcAoVUeQZpI3HDbVEHTwiSdfp4lMg/bTPy+VXvXNLidU/fOwIxD/UjQA==)
    url: jdbc:mariadb://localhost:3306/whive?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Rlatlr7763
    driverClassName: org.mariadb.jdbc.Driver
    validationTimeout: 300000
    #   test-while-idle: true
    #   validation-query: SELECT 1
    #   time-between-eviction-runs-millis: 60000
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
  #   hikari:
  #     idle-timeout: 600000
  #     validationTimeout: 300000
  servlet:
    session:
      timeout: 43200m      # 60m * 24h * 30d
      tracking-modes: cookie
      cookie:
        max-age: 43200m    # 60m * 24h * 30d
        name: SID
        http-only: true
        secure: true
    multipart:
      maxFileSize: -1
      maxRequestSize: 128MB
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    emailname: cs_whive@inswave.com
    emailpassword: xjdtpqcmpcuazjov
    whiveDomain: "https://dev.w-hive.io"
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
server:
  port: 9095 # 9095, 9098
whive:
  password: "test"
  distribution:
    macPassword: "Rlatlr7763"
    deployLogPath: "/Users/jeongsikkim/Documents/w-hive-logfile/"
    deployExportDownloadPath: "/Users/jeongsikkim/w-hive/manager/exportdownload/"
    deployDownloadTempPath: "/Users/jeongsikkim/Documents/headquater_download_temp/"
    deployProvisionfilePath: "/Users/jeongsikkim/profileSet/"
    deployQRCodeUrlPath: "AppFileDir/"
    localgitUrl: "git-admin@localhost:/Users/git-admin/GitRepo/"
    localsvnUrl: "svn+ssh://127.0.0.1/Users/svn-admin/SvnRepo/"
  server:
    whubTarget: "http://192.168.150.94:1337"
    type: "onpremiss"
  hazelcast:
    config: classpath:/hazelcast.yaml
    cluster:
      use: true
  jwt:
    secret: "whivejwtsecretparsetargettobase64"
logging:
  config:
    classpath: logback-spring.xml
  file: "/Users/jeongsikkim/logs"
  level:
    root: INFO
    #    org.springframework.boot: DEBUG
    org.springframework.web: INFO
    com.inswave.whive: INFO
cloud:
  aws:
    credentials:
      accessKey: ''
      secretKey: '''
    s3:
      bucket: '''
    region:
      static: '''
    stack:
      auto: false
defaultBinaryBufferSize: 65536
maxBinaryBufferSize: 67108864