package com.inswave.whive.common.enums;

public enum ClientMessageType {
    HV_MSG_USER_LOGIN_SESSION_INFO,
    HV_MSG_BRANCH_WEBSOCKET_CONNECTION_INFO,
    HV_MSG_CONNETCION_CHECK_INFO,
    HV_MSG_CONNETCION_CHECK_INFO_FROM_HEADQUATER,

    HV_MSG_LOG_INFO,
    HV_MSG_FORCE_LOGOUT,
    HV_MSG_WORKSPACE_CREATE_INFO,
    HV_MSG_PROJECT_CREATE_INFO,
    HV_MSG_PROJECT_CREATE_GITHUB_CLONE_INFO,
    HV_MSG_PROJECT_CREATE_GITHUB_CLONE_INFO_FROM_HEADQUATER,
    HV_MSG_PROJECT_CREATE_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_APP_CONFIG_INFO,

    HV_MSG_BUILD_STATUS_INFO_FROM_HEADQUATER,
    HV_MSG_DEBUG_BUILD,
    HV_MSG_RELEASE_BUILD,
    HV_MSG_LOG_INFO_FROM_BRANCH,
    HV_MSG_BRANCH_INFO,

    HV_MSG_PLUGIN_LIST_INFO,
    HV_MSG_PLUGIN_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_PLUGIN_ADD_LIST_INFO,
    HV_MSG_PLUGIN_ADD_LIST_INFO_FROM_HEADQUATER,
    HV_MSG_PLUGIN_REMOVE_LIST_INFO,
    HV_MSG_PLUGIN_REMOVE_LIST_INFO_FROM_HEADQUATER,

    MV_MSG_SIGNIN_KEY_ADD_INFO,
    MV_MSG_SIGNIN_KEY_ADD_INFO_FROM_HEADQUATER,

    HV_MSG_LOGFILE_DOWNLOAD_INFO,

    HV_MSG_APPFILE_DOWNLOAD_INFO,

    HV_MSG_APPICON_IMAGE_LOAD_INFO,

    HV_MSG_DISCONNECT,
    HV_MSG_DISCONNECT_FROM_BRANCH,

    HV_MSG_BRANCH_SESSID_INFO,
    HV_MSG_HEADQUATER_SESSID_INFO,
    HV_MSG_BRANCH_SESSID_INFO_FROM_BRANCH,

    HV_MSG_SEND_FILE_INFO,
    HV_MSG_SEND_FILE_BLOB,
    HV_MSG_SEND_FILE_INFO_FROM_BRANCH,

    HV_MSG_APP_DOWNLOAD_ACTION_INFO,
    HV_MSG_APP_DOWNLOAD_ACTION_INFO_FROM_HEADQUATER,
    HV_MSG_APP_DOWNLOAD_STATUS_INFO_FROM_HEADQUATER,

    HV_MSG_WINDOWS_CONFIG_LIST_INFO,
    HV_MSG_WINDOWS_CONFIG_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_PONG_CONN_CHK,
    HV_MSG_PROEJCT_PULL_INFO,

    BIN_FILE_SIGNINGKEY_SEND_INFO,
    BIN_FILE_ZIPFILE_SEND_INFO,

    HV_MSG_PROJECT_APP_CONFIG_IMAGE_LIST_INFO_FROM_HEADQUATER,

    HV_MSG_PROJECT_PULL_GITHUB_CLONE_INFO_FROM_HEADQUATER,

    CL_MSG_UPDATE_CHECK,
    CL_MSG_ERROR_UNIQUEID_EMPTY,
    CL_MSG_ERROR_MSGTYPE,
    SVR_BUILB_INFO


}
