spring:
  profiles:
    active: builder_all
---
spring:
  profiles: builder_all
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
      enabled: true
server:
  port: 8085
whive:
  server:
    target: http://127.0.0.1:8080
  ftpserver:
    storeUrl: "https://store.inswave.kr/"
    manifestUrl: "itms-services://?action=download-manifest&url="
    target: "192.168.0.1"
    port: 0
    user: "ser"
    password: "ser"
  gitserver:
    target: "localhost"
    port: 22
    user: "git-admin"
    password: "inswave!1"
  branch:
    id: "4"
    name: "BranchService"
    sessType: "BRANCH"
    position: "MAC"
    password: "builder123!1"
  distribution:
    UserRootPath: "/w-hive/builder/"
    UserGitRepositoryPath: "/Users/git-admin/GitRepo/"
    UserSvnRepositoryPath: "/Users/svn-admin/SvnRepo/"
    WindowsRootPath: ""
    profilePath: "/w-hive/builder/fileTempDir/"
    UserBranchResource: "/branch/src/main/resources"
    AndroidAppIconPath: "/app/src/main/res"
    AndoridLogohdpiPath: "/app/src/main/res/mipmap-hdpi/"
    AndoridLogomdpiPath: "/app/src/main/res/mipmap-mdpi/"
    AndoridLogoxhdpiPath: "/app/src/main/res/mipmap-xhdpi/"
    iOSAppIconPath: "/Assets.xcassets/AppIcon.appiconset/"
    deployLogPath: "/w-hive/builder/builder_logfile/"
    signingkeyPath: "/w-hive/builder/signingkey/"
    deployWindowsLogPath: "C:\\Hive\\log\\"
    ftpAppFilePath: "/var/www/html/ser-stor/webapps/ROOT/app/"
    WMatrixPluginPathAndroid: "/w-hive/builder/plugin/Android/wmatrix"
    WMatrixPluginPathiOS: "/w-hive/builder/plugin/iOS/wmatrix"
    PluginPathAndroid: "/w-hive/builder/plugin/Android/whybrid"
    PluginPathiOS: "/w-hive/builder/plugin/iOS/whybrid"
    wmatrixmanager: "/usr/local/bin/wmatrixmanager"
websocketaddress: 'ws://localhost:8080/whivebranch'
logging:
  config:
    classpath: logback-spring.xml
  file: "/Users/uapmobile/logs"
  level:
    #    org.springframework.boot: DEBUG
    org.springframework.web: INFO
    com.inswave.whive: INFO