package com.inswave.whive.branch.enums;

/* ***********
* branch 서비스 Message Type 명 관리 enum
* 새로운 기능을 추가할 때 Message Type 을 추가.
* 네이밍 규칙은 HV_MSG 앞에 기본으로 명하고
* DEBUG_BUILD 뒤에 기능을 쉽게 인지하게 넣어둔다.
* HV_MSG_DEBUG_BUILD
*
*
*

 */
public enum BuildServiceType {
    HV_MSG_BRANCH_WEBSOCKET_CONNECTION_INFO,
    HV_MSG_CONNETCION_CHECK_INFO,
    HV_MSG_BRANCH_SESSID_INFO,

    HV_MSG_DEBUG_BUILD,
    HV_MSG_RELEASE_BUILD,
    HV_MSG_AAB_DEBUG_BUILD,
    HV_MSG_AAB_RELEASE_BUILD,
    HV_MSG_MULTI_PROFILE_IOS_BUILD,

    HV_MSG_RELEASE_BUILD_FROM_BRANCH,
    HV_MSG_BUILD_STATUS_INFO,
    HV_MSG_LOG_INFO,

    HV_MSG_PLUGIN_ADD_LIST_INFO,
    HV_MSG_PLUGIN_REMOVE_LIST_INFO,
    HV_MSG_PLUGIN_LIST_INFO,

    MV_MSG_SIGNIN_KEY_ADD_INFO,
    HV_MSG_APP_DOWNLOAD_ACTION_INFO,
    BIN_FILE_SIGNINGKEY_SEND_INFO,

    MV_BIN_SINGING_KEY_ADD_INFO,

    HV_MSG_LOGFILE_DOWNLOAD_INFO,
    HV_MSG_LOGFILE_DOWNLOAD_INFO_FROM_BRANCH,

    HV_MSG_BUILD_ALL_MULTI_PROFILE_LIST_INTO,
    HV_MSG_BUILD_SET_ACTIVE_PROFILE_INFO,
    HV_MSG_BUILD_GET_MULTI_PROFILE_APPCONFIG_LIST_INFO,
    HV_MSG_PROJECT_UPDATE_MULTI_PROFILE_CONFIG_UPDATE_INFO,

    HV_MSG_PROJECT_UPDATE_VCS_MULTI_PROFILE_CONFIG_UPDATE_INFO,

    HV_MSG_GENERAL_ANDROID_DEBUG_BUILD,
    HV_MSG_GENERAL_ANDROID_RELEASE_BUILD,
    HV_MSG_GENERAL_ANDROID_AAB_DEBUG_BUILD,
    HV_MSG_GENERAL_ANDROID_AAB_RELEASE_BUILD,
    HV_MSG_GENERAL_IOS_DEBUG_BUILD,
    HV_MSG_GENERAL_IOS_RELEASE_BUILD
}
