package com.inswave.whive.branch.enums;

public enum DeployServiceType {
    HV_MSG_DEPLOY_ALPHA_INFO,
    HV_MSG_DEPLOY_BETA_INFO,
    HV_MSG_DEPLOY_REAL_DEPLOY_INFO,
    HV_MSG_DEPLOY_STATUS_INFO,
    HV_MSG_DEPLOY_SETTING_INIT_INFO,

    HV_MSG_DEPLOY_TASK_UPDATE_STATUS_INFO,

    HV_MSG_DEPLOY_TASK_SEARCH_STATUS_INFO,

    HV_MSG_DEPLOY_METADATA_UPDATE_STATUS_INFO,

    HV_MSG_DEPLOY_METADATA_SEARCH_STATUS_INFO,

    HV_MSG_DEPLOY_METADATA_IMAGE_STATUS_INFO
}
